x-airflow-common:
  &airflow-common
  build: .
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    # Mengotomatiskan koneksi bernama 'postgres_default' agar langsung terhubung:
    AIRFLOW_CONN_POSTGRES_DEFAULT: 'postgresql+psycopg2://airflow:airflow@postgres:5432/airflow'
    AIRFLOW__WEBSERVER__SECRET_KEY: 'kunci_rahasia_airflow_dwbi'
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
  volumes:
    - ./dags:/opt/airflow/dags
    - ./data:/opt/airflow/data
    - ./sql:/opt/airflow/sql
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5430:5432" # Port 5430 untuk Anda akses dari laptop (misal via DBeaver)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5

  webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always

volumes:
  postgres_data: